# Production-specific overrides
services:
  traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.kraeuterakademie.it`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH}"

  nuxt:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nuxt.rule=Host(`kraeuterakademie.it`,`www.kraeuterakademie.it`)"
      - "traefik.http.routers.nuxt.entrypoints=websecure"
      - "traefik.http.routers.nuxt.tls.certresolver=letsencrypt"
      - "traefik.http.services.nuxt.loadbalancer.server.port=3000"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  storybook:
    image: ghcr.io/felixrizzolli/kraeuterakademie-it-storybook:${STORYBOOK_VERSION:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storybook.rule=Host(`storybook.kraeuterakademie.it`)"
      - "traefik.http.routers.storybook.entrypoints=websecure"
      - "traefik.http.routers.storybook.tls.certresolver=letsencrypt"
      - "traefik.http.services.storybook.loadbalancer.server.port=6006"
    networks:
      - kraeuterakademie

  strapi:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi.rule=Host(`api.kraeuterakademie.it`)"
      - "traefik.http.routers.strapi.entrypoints=websecure"
      - "traefik.http.routers.strapi.tls.certresolver=letsencrypt"
      - "traefik.http.services.strapi.loadbalancer.server.port=1337"
    volumes:
      - ./data/strapi-uploads:/opt/app/public/uploads
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 512M